export const GLOBAL = [
  {  // en
    QRPay: "QR Pay",
    Connect: "Connect",
    Recharge: "Recharge",
    Transfer: "Transfer",
    Receive: "Receive",
    PhoneCard: "Phone card",
    Bill: "Bill",
    MovieTicket: "Movie Ticket",
    AirTicket: "Air ticket",
    CreatePin: "Create PIN CODE success",
    SorryBlock: "Sorry you was BLOCKED",
    ReceivedMoney: "YOU RECEIVED MONEY",
    MoneyTrans: "MONEY TRANSACTION",
    IdTrans: "Id transaction",
    DesTrans: "Description",
    Close: "Close",
    ReceiveTrans: "Received money from ",
    TransferTrans: "Transfer money to ",
    RechargeTrans: "Recharged to Tri-T Pay",
    EmailPhone: "Email / Phone",
    Password: "Password",
    SignIn: "Sign In",
    ForgotPassword: "Forgot password ?",
    SIGNIN: "SIGN IN",
    SIGNUP: "SIGN UP",
    Send: "Send",
    Name: "Name",
    PhoneNumber: "Phone number",
    VerifyCode: "Verify Code",
    ConfirmPassword: "Confirm Password",
    Register: "Register",
    RegisterEccept: "Registered you have accepted ",
    TermOfUse: "the terms of use",
    GetThePassword: "Get the password",
    ProvideEmailAddress: "Please provide information to get the password",
    FORGOTPASS: 'Forgot password',
    SendPassSuccess: "Send password success",
    HOME: "Home",
    TRANSACTION: "Transaction",
    PROMOTION: "Promotion",
    USER: "User",
    HighProtectAccount: "High Protect Account",
    ConnectSocial: "Connect Social",
    PayAccount: "Pay Account",
    GiftsList : "Gifts List",
    Support: "Support",
    QuickFeedback: "Quick Feedback",
    AboutApp: "About Tri-T Pay",
    SignOut: "Sign out",
    LogoutSuccess: "Log out successfully",
    ProfileSetting: "Profile Setting",
    CurrentCurrency: "Current currency",
    EnterMoney: "Enter money",
    Confirm: "Confirm",
    EnterPass2Recharge: "Enter password to recharge",
    RechargeSuccess: "RECHARGE SUCCESS ",
    RechargeFail: "RECHARGE FAIL ",
    RechargeMoney: "Recharge money ",
    RechargeId: "Recharge Id",
    ServiceType: "Service type ",
    FeeRecharge: "Fee recharge ",
    Time: "Time ",
    Promotion: "Promotion ",
    Recharge: "Recharge",
    PromotionId: "Promotion Id ",
    Free: "Free",
    No: "No",
    TransactionHistory: "Transaction History",
    DETAIL_TRANSACTION: "DETAIL TRANSACTION",
    MONEY_TRANSACTION: "MONEY TRANSACTION",
    Target: "Target",
    TranId: "TranId",
    Fee: "Fee",
    Date: "Date",
    Type: "Type",
    Language: "Language",
    ResetLanguage: "You must restart app to apply new language",
    OK:"OK",
    Cancel:"Cancel",
    TypeTransaction:["Transfer","Pay","Recharge","Receive"],
    Error:["Money no enough","Wrong security password","Network error"],
    TRANSACTION_SUCCESS: "TRANSACTION SUCCESS",
    TRANSACTION_FAIL: "TRANSACTION FAIL",
    ReceiveUser: "Receive User",
    EnterPass2Transfer: "Enter password to transfer",
    Transfer2Friend: "Transfer to friend",
    PhoneLib:"Phone, library",
    EnterPhone: "Enter phone number"    ,
    TransferBank: "Transfer to bank"
  }, 
  { // vi
    QRPay: "Quét mã",
    Connect: "Liên kết",
    Recharge: "Nạp tiền",
    Transfer: "Chuyển tiền",
    Receive: "Nhận tiền",
    PhoneCard: "Thẻ điện thoại",
    Bill: "Hóa đơn",
    MovieTicket: "Vé xem phim",
    AirTicket: "Vé máy bay",
    CreatePin: "Tạo mã PIN thành công",
    SorryBlock: "Xin lỗi bạn đã bị khóa",
    ReceivedMoney: "BẠN ĐÃ NHẬN ĐƯỢC TIỀN",
    MoneyTrans: "SỐ TIỀN GIAO DỊCH",
    IdTrans: "Số tiền giao dịch",
    DesTrans: "Mô tả",
    Close: "Đóng",
    ReceiveTrans: "Nhận tiền từ ",
    TransferTrans: "Chuyển tiền tới ",
    RechargeTrans: "Nạp tiền vào Tri-T Pay",
    EmailPhone: "Email / Số điện thoại",
    Password: "Mật khẩu",
    SignIn: "Đăng nhập",
    ForgotPassword: "Quên mật khẩu ?",
    SIGNIN: "ĐĂNG NHẬP",
    SIGNUP: "ĐĂNG KÝ",
    Send: "Gửi",
    Name: "Tên",
    PhoneNumber: "Số điện thoại",
    VerifyCode: "Mã xác thực",
    ConfirmPassword: "Xác nhận mật khẩu",
    Register: "Đăng ký",
    RegisterEccept: "Đăng ký bạn đã chấp nhận ",
    TermOfUse: "điều khoản sử dụng",
    GetThePassword: "Lấy lại mật khẩu",
    ProvideEmailAddress: "Xin hãy cung cấp thông tin để lấy lại mật khẩu",
    FORGOTPASS: 'Quên mật khẩu',
    SendPassSuccess: "Gửi mật khẩu thành công",
    HOME: "Trang chủ",
    TRANSACTION: "Giao dịch",
    PROMOTION: "Khuyến mãi",
    USER: "Tài khoản",
    HighProtectAccount: "Thiết lập bảo vệ tài khoản",
    ConnectSocial: "Liên kết mạng xã hội",
    PayAccount: "Tài khoản thanh toán",
    GiftsList : "Danh sách quà tặng",
    Support: "Hỗ trợ",
    QuickFeedback: "Phản hồi nhanh",
    AboutApp: "Thông tin về Tri-T Pay",
    SignOut: "Đăng xuất",
    LogoutSuccess: "Đăng xuất thành công",
    ProfileSetting: "Thiết lập tài khoản",
    CurrentCurrency: "Số dư hiện tại",
    EnterMoney: "Nhập số tiền",
    Confirm: "Xác nhận",
    EnterPass2Recharge: "Nhập mật khẩu để nạp tiền",
    RechargeSuccess: "NẠP TIỀN THÀNH CÔNG ",
    RechargeFail: "NẠP TIỀN THẤT BẠI ",
    RechargeMoney: "Số tiền giao dịch ",
    RechargeId: "Mã nạp tiền",
    ServiceType: "Loại dịch vụ ",
    FeeRecharge: "Phí giao dịch ",
    Time: "Thời gian ",
    Promotion: "Khuyến mãi ",
    Recharge: "Nạp tiền",
    PromotionId: "Mã giảm giá ",
    Free: "Miễn phí",
    No: "Không có",
    TransactionHistory: "Lịch sử giao dịch",
    DETAIL_TRANSACTION: "THÔNG TIN GIAO DỊCH",
    MONEY_TRANSACTION: "SỐ TIỀN GIAO DỊCH",
    Target: "Từ",
    TranId: "Id giao dịch",
    Fee: "Phí",
    Date: "Ngày",
    Type: "Loại",
    Language: "NGÔN NGỮ",
    ResetLanguage: "Bạn phải khởi đội lại phần mềm để sủ dụng ngôn ngữ mới",
    OK:"OK",
    Cancel:"Cancel",
    TypeTransaction:["Chuyển tiền","Thanh toán","Nạp tiền","Nhận tiền"],
    Error:["Không đủ số dư","Sai mật khẩu bảo mật","Lỗi đường truyền"],
    TRANSACTION_SUCCESS: "GIAO DỊCH THÀNH CÔNG",
    TRANSACTION_FAIL: "GIAO DỊCH THẤT BẠI",
    ReceiveUser: "Người nhận",
    EnterPass2Transfer: "Nhập mật khẩu để giao dịch",
    Transfer2Friend: "Chuyển tiền cho bạn bè",
    PhoneLib:"Số điện thoại, danh bạ"   ,
    EnterPhone: "Nhập số điện thoại" ,
    TransferBank: "Chuyển khoản đến ngân hàng"
  } ,
  {
    QRPay: "コードリーダー", //
    Connect: "接続",　//
    Recharge: "リチャージ", //
    Transfer: "振替", //
    Receive: "受ける",//
    PhoneCard: "テレフォンカード",//
    Bill: "付け",//
    MovieTicket: "映画のチケット",//
    AirTicket: "空港のチケット",//
    CreatePin: "成功PINを樹立",//
    SorryBlock: "すみません！プロックス",//
    ReceivedMoney: "あなたは成功お金をくれました",//
    MoneyTrans: "商売のお金",//
    IdTrans: "商売のID",//
    DesTrans: "記述",//
    Close: "閉める",//
    ReceiveTrans: "からお金を入れる",//
    TransferTrans: "までお金を振替する",//
    RechargeTrans: "Tri-Tのリチャージ",//
    EmailPhone: "メール / テレフォン番号",//
    Password: "合言葉",//
    SignIn: "加入",//
    ForgotPassword: "合言葉を忘れる  ?",//
    SIGNIN: "加入",//
    SIGNUP: "サインアップ",//
    Send: "送る",//
    Name: "名前",//
    PhoneNumber: "電話番号",//
    VerifyCode: "ベリファイコード",//
    ConfirmPassword: "合言葉を結ぶ",//
    Register: "サインアップ",//
    RegisterEccept: "Đăng ký bạn đã chấp nhận ",//
    TermOfUse: "điều khoản sử dụng",//
    GetThePassword: "合言葉を入れる",
    ProvideEmailAddress: "　合言葉を入れるのに情報を供給してください",
    FORGOTPASS: '合言葉を忘れる',
    SendPassSuccess: "成功合言葉を送る",
    HOME: "ホーム",
    TRANSACTION: "商売",
    PROMOTION: "キャンペーン",
    USER: "利用者",
    HighProtectAccount: "利用者のプロテクト",
    ConnectSocial: "ソーシャルを接続する",
    PayAccount: "払いの利用者",
    GiftsList : "ギフトのリスト",
    Support: "サポート",
    QuickFeedback: "速いフィードバック",
    AboutApp: "Tri-Tの情報",
    SignOut: "サインアウト",
    LogoutSuccess: "ログアウトが成功です",
    ProfileSetting: "利用者をセッティング",
    CurrentCurrency: "今のお金",
    EnterMoney: "お金を書いて下さい",
    Confirm: "確認",
    EnterPass2Recharge: "　お金のリチャージのに合言葉を入れる",
    RechargeSuccess: "お金のリチャージが成功です",
    RechargeFail: "お金のリチャージが成功でわない",
    RechargeMoney: "リチャージのお金",
    RechargeId: "リチャージのID",
    ServiceType: "サービス型",
    FeeRecharge: "リチャージの料金",
    Time: "時間 ",
    Promotion: "キャンペーン ",
    Recharge: "リチャージ",
    PromotionId: "IDのキャンペーン ",
    Free: "無料",
    No: "いいえ",
    TransactionHistory: "商売の歴史",
    DETAIL_TRANSACTION: "商売の情報",
    MONEY_TRANSACTION: "商売のお金",
    Target: "対象",
    TranId: "IDの商売",
    Fee: "料金",
    Date: "日",
    Type: "型",
    Language: "言葉",
    ResetLanguage: "あなたはベトナムからきましたか？",
    OK:"はい",
    Cancel:"いいえ",
    TypeTransaction:["Chuyển tiền","Thanh toán","Nạp tiền","Nhận tiền"],
    Error:["Không đủ số dư","Sai mật khẩu bảo mật","Lỗi đường truyền"],
    TRANSACTION_SUCCESS: "商売が成功です",
    TRANSACTION_FAIL: "商売が失敗です",
    ReceiveUser: "利用者",
    EnterPass2Transfer: "振替のに合言葉を入れる",
    Transfer2Friend: "友達に商売する",
    PhoneLib:"電話、図書館"    ,
    EnterPhone: "電話をいれる" ,
    TransferBank: "　銀行をいれる"
  } 
];