export const GLOBAL = [
  {  // en
    QRPay: "QR Pay",
    Connect: "Connect",
    Recharge: "Recharge",
    Transfer: "Transfer",
    Receive: "Receive",
    PhoneCard: "Phone card",
    Bill: "Bill",
    MovieTicket: "Movie Ticket",
    AirTicket: "Air ticket",
    CreatePin: "Create PIN CODE success",
    SorryBlock: "Sorry you was BLOCKED",
    ReceivedMoney: "YOU RECEIVED MONEY",
    MoneyTrans: "MONEY TRANSACTION",
    IdTrans: "Id transaction",
    DesTrans: "Description",
    Close: "Close",
    ReceiveTrans: "Received money from ",
    TransferTrans: "Transfer money to ",
    RechargeTrans: "Recharged money to Tri-T Pay",
    EmailPhone: "Email / Phone",
    Password: "Password",
    SignIn: "Sign In",
    ForgotPassword: "Forgot password ?",
    SIGNIN: "SIGN IN",
    SIGNUP: "SIGN UP",
    Send: "Send",
    Name: "Name",
    PhoneNumber: "Phone number",
    VerifyCode: "Verify Code",
    ConfirmPassword: "Confirm Password",
    Register: "Register",
    RegisterEccept: "Registered you have accepted ",
    TermOfUse: "the terms of use",
    GetThePassword: "Get the password",
    ProvideEmailAddress: "Please provide information to get the password",
    FORGOTPASS: 'Forgot password',
    SendPassSuccess: "Send password success",
    HOME: "Home",
    TRANSACTION: "Transaction",
    PROMOTION: "Promotion",
    USER: "User",
    HighProtectAccount: "High Protect Account",
    ConnectSocial: "Connect Social",
    PayAccount: "Pay Account",
    GiftsList : "Gifts List",
    Support: "Support",
    QuickFeedback: "Quick Feedback",
    AboutApp: "About Tri-T Pay",
    SignOut: "Sign out",
    LogoutSuccess: "Log out successfully",
    ProfileSetting: "Profile Setting",
    CurrentCurrency: "Current currency",
    EnterMoney: "Enter money",
    Confirm: "Confirm",
    EnterPass2Recharge: "Enter password to recharge",
    RechargeSuccess: "RECHARGE SUCCESS ",
    RechargeFail: "RECHARGE FAIL ",
    RechargeMoney: "Recharge money ",
    RechargeId: "Recharge Id",
    ServiceType: "Service type ",
    FeeRecharge: "Fee recharge ",
    Time: "Time ",
    Promotion: "Promotion ",
    Recharge: "Recharge",
    PromotionId: "Promotion Id ",
    Free: "Free",
    No: "No"
  }, 
  { // vi
    QRPay: "Quét mã",
    Connect: "Liên kết",
    Recharge: "Nạp tiền",
    Transfer: "Chuyển tiền",
    Receive: "Nhận tiền",
    PhoneCard: "Thẻ điện thoại",
    Bill: "Hóa đơn",
    MovieTicket: "Vé xem phim",
    AirTicket: "Vé máy bay",
    CreatePin: "Tạo mã PIN thành công",
    SorryBlock: "Xin lỗi bạn đã bị khóa",
    ReceivedMoney: "BẠN ĐÃ NHẬN ĐƯỢC TIỀN",
    MoneyTrans: "SỐ TIỀN GIAO DỊCH",
    IdTrans: "Số tiền giao dịch",
    DesTrans: "Mô tả",
    Close: "Đóng",
    ReceiveTrans: "Nhận tiền từ ",
    TransferTrans: "Chuyển tiền tới ",
    RechargeTrans: "Nạp tiền vào tài khoản Tri-T Pay",
    EmailPhone: "Email / Số điện thoại",
    Password: "Mật khẩu",
    SignIn: "Đăng nhập",
    ForgotPassword: "Quên mật khẩu ?",
    SIGNIN: "ĐĂNG NHẬP",
    SIGNUP: "ĐĂNG XUẤT",
    Send: "Gửi",
    Name: "Tên",
    PhoneNumber: "Số điện thoại",
    VerifyCode: "Mã xác thực",
    ConfirmPassword: "Xác nhận mật khẩu",
    Register: "Đăng ký",
    RegisterEccept: "Đăng ký bạn đã chấp nhận ",
    TermOfUse: "điều khoản sử dụng",
    GetThePassword: "Lấy lại mật khẩu",
    ProvideEmailAddress: "Xin hãy cung cấp thông tin để lấy lại mật khẩu",
    FORGOTPASS: 'Quên mật khẩu',
    SendPassSuccess: "Gửi mật khẩu thành công",
    HOME: "Trang chủ",
    TRANSACTION: "Giao dịch",
    PROMOTION: "Khuyến mãi",
    USER: "Tài khoản",
    HighProtectAccount: "Thiết lập bảo vệ tài khoản",
    ConnectSocial: "Liên kết mạng xã hội",
    PayAccount: "Tài khoản thanh toán",
    GiftsList : "Danh sách quà tặng",
    Support: "Hỗ trợ",
    QuickFeedback: "Phản hồi nhanh",
    AboutApp: "Thông tin về Tri-T Pay",
    SignOut: "Đăng xuất",
    LogoutSuccess: "Đăng xuất thành công",
    ProfileSetting: "Thiết lập tài khoản",
    CurrentCurrency: "Số dư hiện tại",
    EnterMoney: "Nhập số tiền",
    Confirm: "Xác nhận",
    EnterPass2Recharge: "Nhập mật khẩu để nạp tiền",
    RechargeSuccess: "NẠP TIỀN THÀNH CÔNG ",
    RechargeFail: "NẠP TIỀN THẤT BẠI ",
    RechargeMoney: "Số tiền giao dịch ",
    RechargeId: "Mã nạp tiền",
    ServiceType: "Loại dịch vụ ",
    FeeRecharge: "Phí giao dịch ",
    Time: "Thời gian ",
    Promotion: "Khuyến mãi ",
    Recharge: "Nạp tiền",
    PromotionId: "Mã giảm giá ",
    Free: "Miễn phí",
    No: "Không có"
  } 
];