const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const GET_REGISTER_ERRORS = 'GET_REGISTER_ERRORS';
const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
const SEND_FORGOT_PASSWORD_SUCCESS = 'SEND_FORGOT_PASSWORD_SUCCESS';
export { 
  GET_LOGIN_ERRORS,
  LOGIN_SUCCESS,
  GET_REGISTER_ERRORS,
  FORGOT_PASSWORD,
  SEND_FORGOT_PASSWORD_SUCCESS
};