const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const GET_REGISTER_ERRORS = 'GET_REGISTER_ERRORS';

export { 
  GET_LOGIN_ERRORS,
  LOGIN_SUCCESS,
  GET_REGISTER_ERRORS
};