
const KEY_BOARD_CLICK = 'KEY_BOARD_CLICK';
const KEY_BOARD_DELETE_CLICK = 'KEY_BOARD_DELETE_CLICK';
const UPDATE_USER_MONEY_DATA = 'UPDATE_USER_MONEY_DATA';

export {
  KEY_BOARD_CLICK,
  KEY_BOARD_DELETE_CLICK,
  UPDATE_USER_MONEY_DATA
};